### ISSUE TITLE
Panel doesn't work

### ISSUE THREAD

**Issue by hez2010** [limefrogyank/BlazorFabric#109]
BlazorFabric: 2.2.0
.NET Core: 3.1.102
Blazor: 3.2.0-preview1.20073.1

```html
<PrimaryButton OnClick="_ => isOpen = true">Open</PrimaryButton>
<Panel IsLightDismiss="true" IsOpen="isOpen">
    <NavigationTemplate>
        <IconButton IconName="GlobalNavButton" OnClick="_ => isOpen = false" />
    </NavigationTemplate>
    <ChildContent>
        <p>Test</p>
    </ChildContent>
</Panel>

@code {
    private bool isOpen;
}
```

After clicking the Open button:
```
Uncaught (in promise) Error: Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Double. Path: $ | LineNumber: 0 | BytePositionInLine: 4.. See InnerException for more details. ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Double. Path: $ | LineNumber: 0 | BytePositionInLine: 4. ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
  at System.Text.Json.Utf8JsonReader.TryGetDouble (System.Double& value) <0x22b6210 + 0x0001a> in <filename unknown>:0 
  at System.Text.Json.Utf8JsonReader.GetDouble () <0x22b6140 + 0x00008> in <filename unknown>:0 
  at System.Text.Json.Serialization.Converters.JsonConverterDouble.Read (System.Text.Json.Utf8JsonReader& reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) <0x22b3e58 + 0x00004> in <filename unknown>:0 
  at System.Text.Json.JsonPropertyInfoNotNullable`4[TClass,TDeclaredProperty,TRuntimeProperty,TConverter].OnRead (System.Text.Json.ReadStack& state, System.Text.Json.Utf8JsonReader& reader) <0x235c280 + 0x00032> in <filename unknown>:0 
  at System.Text.Json.JsonPropertyInfo.Read (System.Text.Json.JsonTokenType tokenType, System.Text.Json.ReadStack& state, System.Text.Json.Utf8JsonReader& reader) <0x1f6e480 + 0x0007e> in <filename unknown>:0 
  at System.Text.Json.JsonSerializer.HandleNull (System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& state) <0x21f6e58 + 0x00108> in <filename unknown>:0 
  at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x1f6adb8 + 0x00274> in <filename unknown>:0 
   --- End of inner exception stack trace ---
  at System.Text.Json.ThrowHelper.ReThrowWithPath (System.Text.Json.ReadStack& readStack, System.Text.Json.Utf8JsonReader& reader, System.Exception ex) <0x239f350 + 0x00028> in <filename unknown>:0 
  at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x1f6adb8 + 0x0032a> in <filename unknown>:0 
  at System.Text.Json.JsonSerializer.ReadValueCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x21f62e0 + 0x00546> in <filename unknown>:0 
  at System.Text.Json.JsonSerializer.ReadValueCore (System.Text.Json.Utf8JsonReader& reader, System.Type returnType, System.Text.Json.JsonSerializerOptions options) <0x21ef050 + 0x0003e> in <filename unknown>:0 
  at System.Text.Json.JsonSerializer.Deserialize (System.Text.Json.Utf8JsonReader& reader, System.Type returnType, System.Text.Json.JsonSerializerOptions options) <0x21eef70 + 0x00024> in <filename unknown>:0 
  at Microsoft.JSInterop.JSRuntime.EndInvokeJS (System.Int64 taskId, System.Boolean succeeded, System.Text.Json.Utf8JsonReader& jsonReader) <0x21db8d8 + 0x00050> in <filename unknown>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x23a63b8 + 0x0002c> in <filename unknown>:0 
  at BlazorFabric.Panel.UpdateFooterPositionAsync () <0x2355d30 + 0x000f6> in <filename unknown>:0 
    at Object.endInvokeDotNetFromJS (https://localhost:5001/_framework/blazor.webassembly.js:1:9849)
    at Object.invokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9475)
    at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.js:1:166288)
    at wasm-function[6199]:0x1187e2
    at wasm-function[1432]:0x40349
    at wasm-function[635]:0x146fe
    at wasm-function[4992]:0xeb085
    at wasm-function[3248]:0xa0c7d
    at wasm-function[1328]:0x3b59c
    at wasm-function[438]:0xd514
```

**Comment by hez2010** [comment]
Sorry, I forgot to put Panel in a LayerHost.

Closed.

**Comment by limefrogyank** [comment]
easy mistake to make.  We should have a more meaningful exception for when the LayerHost is missing.
